-- AlterTable
ALTER TABLE "Guest" ADD COLUMN     "going" BOOLEAN,
ALTER COLUMN "firstName" DROP NOT NULL,
ALTER COLUMN "lastName" DROP NOT NULL,
ALTER COLUMN "email" DROP NOT NULL;

-- AlterTable
ALTER TABLE "RSVP" ADD COLUMN     "going" BOOLEAN;
